<a href="https://colab.research.google.com/github/mada29-tech/Forcasting-Sale-Coffe-shop-using-Extreme-Learning-Machine/blob/main/ELM_Phyton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from google.colab import files
filenya = files.upload()
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from scipy.linalg import pinv

Saving test 20%.csv to test 20%.csv


In [ ]:
train = pd.read_csv('traini 80%.csv')
train.head(86)

No   X1   X2   X3   X4  Target/Y
0    1  128  122  110  132       111
1    2  122  110  132  111       129
2    3  110  132  111  129       125
3    4  132  111  129  125       120
4    5  111  129  125  120       118
..  ..  ...  ...  ...  ...       ...
81  82  116  126  125  129       120
82  83  126  125  129  120       118
83  84  125  129  120  118       128
84  85  129  120  118  128       127
85  86  120  118  128  127       117

[86 rows x 6 columns]

In [ ]:
test = pd.read_csv('test 20%.csv')
test.head(22)

No   X1   X2   X3   X4  Target/Y
0    1  118  128  127  117       118
1    2  128  127  117  118       117
2    3  127  117  118  117       127
3    4  117  118  117  127       124
4    5  118  117  127  124       128
5    6  117  127  124  128       122
6    7  127  124  128  122       118
7    8  124  128  122  118       128
8    9  128  122  118  128       129
9   10  122  118  128  129       118
10  11  118  128  129  118       129
11  12  128  129  118  129       127
12  13  129  118  129  127       118
13  14  118  129  127  118       117
14  15  129  127  118  117       124
15  16  127  118  117  124       121
16  17  118  117  124  121       128
17  18  117  124  121  128       123
18  19  124  121  128  123       128
19  20  121  128  123  128       123
20  21  128  123  128  123       129
21  22  123  128  123  129       102

In [ ]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(train.values[:,1:5])
y_train = scaler.fit_transform(train.values[:,5:])

X_test = scaler.fit_transform(test.values[:,1:5])
y_test = scaler.fit_transform(test.values[:,5:])

In [ ]:
print(X_train)

[[0.81818182 0.54545455 0.         1.        ]
 [0.54545455 0.         1.         0.        ]
 [0.         1.         0.04545455 0.85714286]
 [1.         0.04545455 0.86363636 0.66666667]
 [0.04545455 0.86363636 0.68181818 0.42857143]
 [0.86363636 0.68181818 0.45454545 0.33333333]
 [0.68181818 0.45454545 0.36363636 0.9047619 ]
 [0.45454545 0.36363636 0.90909091 0.80952381]
 [0.36363636 0.90909091 0.81818182 0.38095238]
 [0.90909091 0.81818182 0.40909091 0.57142857]
 [0.81818182 0.40909091 0.59090909 0.47619048]
 [0.40909091 0.59090909 0.5        0.71428571]
 [0.59090909 0.5        0.72727273 0.28571429]
 [0.5        0.72727273 0.31818182 0.61904762]
 [0.72727273 0.31818182 0.63636364 0.42857143]
 [0.31818182 0.63636364 0.45454545 0.71428571]
 [0.63636364 0.45454545 0.72727273 0.47619048]
 [0.45454545 0.72727273 0.5        0.23809524]
 [0.72727273 0.5        0.27272727 1.        ]
 [0.5        0.27272727 1.         0.71428571]
 [0.27272727 1.         0.72727273 0.42857143]
 [1.         

In [ ]:
print(X_test)

[[0.08333333 0.91666667 0.83333333 0.        ]
 [0.91666667 0.83333333 0.         0.08333333]
 [0.83333333 0.         0.08333333 0.        ]
 [0.         0.08333333 0.         0.83333333]
 [0.08333333 0.         0.83333333 0.58333333]
 [0.         0.83333333 0.58333333 0.91666667]
 [0.83333333 0.58333333 0.91666667 0.41666667]
 [0.58333333 0.91666667 0.41666667 0.08333333]
 [0.91666667 0.41666667 0.08333333 0.91666667]
 [0.41666667 0.08333333 0.91666667 1.        ]
 [0.08333333 0.91666667 1.         0.08333333]
 [0.91666667 1.         0.08333333 1.        ]
 [1.         0.08333333 1.         0.83333333]
 [0.08333333 1.         0.83333333 0.08333333]
 [1.         0.83333333 0.08333333 0.        ]
 [0.83333333 0.08333333 0.         0.58333333]
 [0.08333333 0.         0.58333333 0.33333333]
 [0.         0.58333333 0.33333333 0.91666667]
 [0.58333333 0.33333333 0.91666667 0.5       ]
 [0.33333333 0.91666667 0.5        0.91666667]
 [0.91666667 0.5        0.91666667 0.5       ]
 [0.5        

In [ ]:
print(y_train)

[[0.        ]
 [0.85714286]
 [0.66666667]
 [0.42857143]
 [0.33333333]
 [0.9047619 ]
 [0.80952381]
 [0.38095238]
 [0.57142857]
 [0.47619048]
 [0.71428571]
 [0.28571429]
 [0.61904762]
 [0.42857143]
 [0.71428571]
 [0.47619048]
 [0.23809524]
 [1.        ]
 [0.71428571]
 [0.42857143]
 [0.66666667]
 [0.52380952]
 [0.66666667]
 [0.33333333]
 [0.76190476]
 [0.85714286]
 [0.52380952]
 [0.57142857]
 [0.61904762]
 [0.28571429]
 [0.95238095]
 [0.76190476]
 [0.28571429]
 [0.14285714]
 [0.57142857]
 [0.47619048]
 [0.76190476]
 [0.57142857]
 [0.33333333]
 [0.71428571]
 [0.23809524]
 [0.85714286]
 [0.47619048]
 [0.66666667]
 [0.76190476]
 [0.38095238]
 [0.66666667]
 [0.71428571]
 [0.80952381]
 [0.33333333]
 [0.71428571]
 [0.85714286]
 [0.61904762]
 [0.76190476]
 [0.33333333]
 [0.66666667]
 [0.52380952]
 [0.47619048]
 [0.80952381]
 [0.23809524]
 [0.42857143]
 [0.9047619 ]
 [0.28571429]
 [0.85714286]
 [0.57142857]
 [0.85714286]
 [0.38095238]
 [0.19047619]
 [0.33333333]
 [0.23809524]
 [0.76190476]
 [0.66

In [ ]:
print(y_test)

[[0.59259259]
 [0.55555556]
 [0.92592593]
 [0.81481481]
 [0.96296296]
 [0.74074074]
 [0.59259259]
 [0.96296296]
 [1.        ]
 [0.59259259]
 [1.        ]
 [0.92592593]
 [0.59259259]
 [0.55555556]
 [0.81481481]
 [0.7037037 ]
 [0.96296296]
 [0.77777778]
 [0.96296296]
 [0.77777778]
 [1.        ]
 [0.        ]]


In [ ]:
input_size = X_train.shape[1]

In [ ]:
print(input_size)

4


In [ ]:
hidden_size = 5

In [ ]:
input_weights = np.random.uniform(low=-1, high=1, size=[input_size,hidden_size])
biases = np.random.uniform(low=-1, high=1, size=[hidden_size])

In [ ]:
print(input_weights)

[[ 0.97104389 -0.18462384 -0.3451008  -0.97619551 -0.07222227]
 [ 0.31157656 -0.97901212 -0.07887925  0.91614522 -0.22035094]
 [-0.52200485  0.50949595  0.11941049 -0.52568867  0.50834106]
 [-0.8751353  -0.96464654 -0.0592115  -0.32098686 -0.8764047 ]]


In [ ]:
print(biases)

[-0.29326175  0.59675308 -0.82783186 -0.73024087  0.4668106 ]


In [ ]:
def sig(x):
 return 1/(1 + np.exp(-x))

In [ ]:
def hidden_nodes(X):
    G = np.dot(X, input_weights)
    G = G + biases
    H = sig(G)
    return H

In [ ]:
output_weights = np.dot(pinv(hidden_nodes(X_train)), y_train)

In [ ]:
def predict(X):
    out = hidden_nodes(X)
    out = np.dot(out, output_weights)
    return out

In [ ]:
prediction = predict(X_test)

In [ ]:
prediction

array([[0.78456331],
       [0.74845004],
       [0.89463429],
       [0.73067307],
       [0.68327266],
       [0.54450625],
       [0.53557747],
       [0.72605438],
       [0.52641335],
       [0.49549226],
       [0.72057137],
       [0.49133157],
       [0.50307998],
       [0.74456092],
       [0.74435689],
       [0.69994428],
       [0.79441659],
       [0.60414996],
       [0.57835646],
       [0.49189396],
       [0.51812376],
       [0.44274389]])

In [ ]:
prediksi = scaler.inverse_transform(prediction)
prediksi

array([[123.1832094 ],
       [122.20815099],
       [126.15512571],
       [121.72817277],
       [120.44836169],
       [116.70166874],
       [116.46059161],
       [121.60346813],
       [116.21316051],
       [115.37829108],
       [121.4554269 ],
       [115.26595237],
       [115.58315955],
       [122.10314494],
       [122.09763606],
       [120.89849556],
       [123.44924801],
       [118.31204894],
       [117.6156244 ],
       [115.28113686],
       [115.98934139],
       [113.95408495]])

In [ ]:
test

No   X1   X2   X3   X4  Target/Y
0    1  118  128  127  117       118
1    2  128  127  117  118       117
2    3  127  117  118  117       127
3    4  117  118  117  127       124
4    5  118  117  127  124       128
5    6  117  127  124  128       122
6    7  127  124  128  122       118
7    8  124  128  122  118       128
8    9  128  122  118  128       129
9   10  122  118  128  129       118
10  11  118  128  129  118       129
11  12  128  129  118  129       127
12  13  129  118  129  127       118
13  14  118  129  127  118       117
14  15  129  127  118  117       124
15  16  127  118  117  124       121
16  17  118  117  124  121       128
17  18  117  124  121  128       123
18  19  124  121  128  123       128
19  20  121  128  123  128       123
20  21  128  123  128  123       129
21  22  123  128  123  129       102

In [ ]:
y_true = np.array(test["X1"])
y_pred = np.array(prediksi)

In [ ]:
def percentage_error(actual, predicted):
    res = np.empty(actual.shape)
    for j in range(actual.shape[0]):
        if actual[j] != 0:
            res[j] = (actual[j] - predicted[j]) / actual[j]
        else:
            res[j] = predicted[j] / np.mean(actual)
    return res

def mean_absolute_percentage_error(y_true, y_pred):
    return np.mean(np.abs(percentage_error(np.asarray(y_true), np.asarray(y_pred)))) * 100

In [ ]:
print("MAPE :", mean_absolute_percentage_error(y_true, y_pred), "%")

MAPE : 5.003778567782984 %


<ipython-input-161-003d5079650a>:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  res[j] = (actual[j] - predicted[j]) / actual[j]
